baseURL = "https://scgajge12.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "morioka12 site"
theme = "gokarna"
googleAnalytics = "G-W4JLNVPRX5"

# Automatically generate robots.txt
enableRobotsTXT = true

[params]
  footer = "scgajge12"
  description = "Japanese Student, Security Engineer and Bug Hunter"
  avatarURL = "/images/morioka12.jpg"
  AvatarAltText = "avatar"
  avatarSize = "size-m"
  accentColor = "#38b48b"
  togglePreviousAndNextButtons = "true"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  socialIcons = [
    {name = "twitter", url = "https://twitter.com/scgajge12"},
    {name = "github", url = "https://github.com/scgajge12"},
    {name = "linkedin", url = "https://www.linkedin.com/in/yuta-morioka-263591230"},
    {name = "email", url = "mailto:morioka1831@gmail.com"}
  ]
  metaKeywords = ["morioka12", "scgajge12", "portfolio"]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    pre = "<span data-feather='user'></span>"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Activities"
    pre = "<span data-feather='activity'></span>"
    url = "/activities/"
    weight = 3

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 4

  [[menu.main]]
    name = "CVEs"
    pre = "<span data-feather='star'></span>"
    url = "/cves/"
    weight = 5

  [[menu.main]]
    name = "Gift"
    pre = "<span data-feather='gift'></span>"
    url = "https://www.amazon.co.jp/hz/wishlist/ls/3PPY9KHO5FSIS?ref_=wl_share"
    weight = 6

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = true

